### ISSUE TITLE
A general Todo list

### ISSUE THREAD

**Issue by SquidDev** [SquidDev/amulet#4]
To-do List
==========

Scale of difficulty, from hardest to easiest:
- `hard!`
- `hard`
- `kinda simple`
- `easy`
- `easy!`

- [ ] Initial language implementation
  - [ ] Abstract syntax tree `kinda simple`
        This isn't so easy because, well, look at the spec! Our grammar's fucking complicated, man.
  - [ ] Lexer  (using `alex`) (simple)
    - [ ] Minimal set of tokens required to parse (simple)
  - [ ] Parser (using `happy`)
    - [ ] Parsing custom operators correctly (hard!)
  - [ ] Type checker (hard!)
    - [ ] Type-driven name resolution (hard!)
    - [ ] Inference (hard)
  - [ ] Code generator (using a fancy-pants MTL stack)
    - [ ] Intermediate representation for optimisations (easy)
      - [ ] Dead code elimination (hard)
      - [ ] Inlining (hard)
      - [ ] Lambda lifting (hard)
      - [ ] Constant folding (kinda simple)
      - [ ] Common subexpression elimination (kinda simple)
      - [ ] Uncurrying on-demand (hard!)
    - [ ] Structured Lua intermediate representation (easy)
      - [ ] Generation (easy)
      - [ ] Emission (easy)

**Comment by demhydraz** [comment]
I'd add

[ ] Compile to LLVM

If all goes well.

**Comment by gforcedev** [comment]
Are you planning to compile to Lua source or Lua bytecode?

**Comment by SquidDev** [comment]
Probably Lua source: Amulet doesn't do anything fancy enough to merit `goto` (which is the only reason to compile to bytecode).

**Comment by demhydraz** [comment]
We've already done module resolution. Twice, by now.

**Comment by SquidDev** [comment]
Development has moved to a different repo, so I think this is dead for now :/.

**Comment by RGFTheCoder** [comment]
what is the new repo?
